package tools

import (
	"regexp"
	"sort"
	"strings"
)

var CountryToCode = map[string]string{
	"europe": "EU", "eu": "EU", "european union": "EU", "euro stoxx": "EU", "eurostoxx": "EU", "european": "EU", "brussels": "EU", "europa": "EU",
	"united states": "US", "usa": "US", "america": "US", "u.s.": "US", "u.s.a.": "US", "us": "US", "U.S.": "US", "U.S": "US", "u.s": "US",
	"s&p 500": "US", "s&p500": "US", "sp500": "US", "s&p": "US",
	"dow jones": "US", "dow": "US", "djia": "US",
	"nasdaq": "US", "nasdaq composite": "US",
	"russell 2000": "US", "russell": "US",
	"vance": "US", "trump": "US", "american": "US",
	"china": "CN", "chinese": "CN", "shanghai": "CN", "shcomp": "CN", "jinping": "CN", "xi": "CN",
	"hong kong": "HK", "hsi": "HK", "hang seng": "HK", "hkg": "HK",
	"beijing": "CN", "prc": "CN",
	"russia": "RU", "russian": "RU", "moscow": "RU", "kremlin": "RU", "putin": "RU",
	"germany": "DE", "german": "DE", "dax": "DE", "dax 40": "DE",
	"berlin": "DE", "bundeswehr": "DE",
	"france": "FR", "french": "FR", "paris": "FR", "macron": "FR", "cac 40": "FR", "cac": "FR",
	"united kingdom": "GB", "uk": "GB", "britain": "GB", "british": "GB", "england": "GB", "english": "GB", "U.K.": "GB", "ftse": "GB", "london": "GB",
	"japan": "JP", "japanese": "JP", "tokyo": "JP", "sdf": "JP", "nikkei": "JP", "nikkei 225": "JP",
	"india": "IN", "indian": "IN", "sensex": "IN", "bse sensex": "IN", "delhi": "IN", "mumbai": "IN", "nifty": "IN", "nifty 50": "IN",
	"italy": "IT", "italian": "IT", "ftse mib": "IT", "mib": "IT", "italians": "IT",
	"spain": "ES", "spanish": "ES", "ibex 35": "ES", "ibex": "ES",
	"canada": "CA", "canadian": "CA", "ottawa": "CA", "cad": "CA",
	"australia": "AU", "australian": "AU", "asx 200": "AU", "asx": "AU", "aud": "AU", "canberra": "AU",
	"brazil": "BR", "brazilian": "BR", "brasil": "BR", "rio de janeiro": "BR", "sao paulo": "BR",
	"mexico": "MX", "mexican": "MX",
	"salvador": "SV", "bukele": "SV",
	"south korea": "KR", "korea": "KR", "korean": "KR", "kospi": "KR", "kosdaq": "KR",
	"seoul": "KR", "rok": "KR",
	"israel": "IL", "israeli": "IL", "israelis": "IL", "jerusalem": "IL", "tel aviv": "IL", "idf": "IL", "mossad": "IL", "shin bet": "IL", "netanyahu": "IL", "zionism": "IL", "zionist": "IL", "zionists": "IL", "jewish": "IL", "jews": "IL",
	"iran": "IR", "iranian": "IR", "iranians": "IR", "tehran": "IR", "persia": "IR", "khamenei": "IR", "rouhani": "IR",
	"turkey": "TR", "turkish": "TR", "ankara": "TR", "erdogan": "TR",
	"saudi arabia": "SA", "saudi": "SA", "riyadh": "SA", "bin salman": "SA", "aramco": "SA",
	"united arab emirates": "AE", "uae": "AE", "emirates": "AE", "abu dhabi": "AE", "dubai": "AE",
	"egypt": "EG", "egyptian": "EG",
	"ukraine": "UA", "ukrainian": "UA", "ukrainians": "UA", "kyiv": "UA", "kiev": "UA", "zelensky": "UA", "zelenskyy": "UA",
	"poland": "PL", "polish": "PL",
	"netherlands": "NL", "dutch": "NL", "hague": "NL", "amsterdam": "NL",
	"belgium": "BE", "belgian": "BE",
	"switzerland": "CH", "swiss": "CH", "franc": "CH", "chf": "CH", "geneva": "CH", "zurich": "CH",
	"austria": "AT", "austrian": "AT",
	"sweden": "SE", "swedish": "SE",
	"norway": "NO", "norwegian": "NO",
	"denmark": "DK", "danish": "DK",
	"finland": "FI", "finnish": "FI",
	"greece": "GR", "greek": "GR",
	"portugal": "PT", "portuguese": "PT",
	"south africa": "ZA",
	"nigeria":      "NG", "nigerian": "NG",
	"taiwan": "TW", "taiwanese": "TW", "taipei": "TW", "roc": "TW",
	"singapore": "SG",
	"malaysia":  "MY", "malaysian": "MY",
	"thailand": "TH", "thai": "TH", "bangkok": "TH",
	"vietnam": "VN", "vietnamese": "VN",
	"indonesia": "ID", "indonesian": "ID",
	"philippines": "PH", "philippine": "PH",
	"argentina": "AR", "argentinian": "AR", "buenos aires": "AR",
	"chile": "CL", "chilean": "CL",
	"colombia": "CO", "colombian": "CO",
	"venezuela": "VE", "venezuelan": "VE",
	"peru": "PE", "peruvian": "PE",
	"ecuador": "EC", "ecuadorian": "EC",
	"bolivia": "BO", "bolivian": "BO",
	"uruguay": "UY", "uruguayan": "UY",
	"paraguay": "PY", "paraguayan": "PY",
	"new zealand": "NZ", "kiwi": "NZ",
	"ireland": "IE", "irish": "IE", "dublin": "IE",
	"czech republic": "CZ", "czechia": "CZ", "czech": "CZ", "prague": "CZ",
	"hungary": "HU", "hungarian": "HU",
	"romania": "RO", "romanian": "RO",
	"qatar":    "QA",
	"kuwait":   "KW",
	"pakistan": "PK", "pakistani": "PK", "islamabad": "PK",
	"bangladesh":  "BD",
	"sri lanka":   "LK",
	"north korea": "KP", "dprk": "KP", "pyongyang": "KP", "kim jong": "KP",
	"myanmar": "MM", "burma": "MM",
	"luxembourg": "LU",
	"iceland":    "IS", "icelandic": "IS",
	"malta": "MT", "maltese": "MT",
	"cyprus": "CY", "cypriot": "CY",
	"algeria": "DZ", "algerian": "DZ",
	"morocco": "MA", "moroccan": "MA",
	"tunisia": "TN", "tunisian": "TN",
	"libya": "LY", "libyan": "LY",
	"senegal": "SN", "senegalese": "SN",
	"ghana": "GH", "ghanaian": "GH",
	"kenya": "KE", "kenyan": "KE",
	"tanzania": "TZ", "tanzanian": "TZ",
	"uganda": "UG", "ugandan": "UG",
	"zimbabwe": "ZW", "zimbabwean": "ZW",
	"angola": "AO", "angolan": "AO",
	"mozambique": "MZ", "mozambican": "MZ",
	"cameroon": "CM", "cameroonian": "CM",
	"ivory coast": "CI", "cote d'ivoire": "CI", "ivorycoast": "CI",
	"malawi": "MW", "malawian": "MW",
	"zambia": "ZM", "zambian": "ZM",
	"ethiopia": "ET", "ethiopian": "ET",
	"somalia": "SO", "somali": "SO",
	"afghanistan": "AF", "afghan": "AF", "kabul": "AF", "taliban": "AF",
	"kazakhstan": "KZ", "kazakh": "KZ",
	"uzbekistan": "UZ", "uzbek": "UZ",
	"turkmenistan": "TM", "turkmen": "TM",
	"kyrgyzstan": "KG", "kyrgyz": "KG",
	"tajikistan": "TJ", "tajik": "TJ",
	"belarus": "BY", "belarusian": "BY",
	"serbia": "RS", "serbian": "RS",
	"bosnia and herzegovina": "BA", "bosnia": "BA", "herzegovina": "BA",
	"montenegro": "ME", "montenegrin": "ME",
	"macedonia": "MK", "north macedonia": "MK", "macedonian": "MK",
	"albania": "AL", "albanian": "AL",
	"moldova": "MD", "moldovan": "MD",
	"georgia": "GE", "georgian": "GE",
	"armenia": "AM", "armenian": "AM",
	"azerbaijan": "AZ", "azerbaijani": "AZ",
	"lithuania": "LT", "lithuanian": "LT",
	"latvia": "LV", "latvian": "LV",
	"estonia": "EE", "estonian": "EE",
	"slovakia": "SK", "slovak": "SK",
	"slovenia": "SI", "slovenian": "SI",
	"croatia": "HR", "croatian": "HR",
	"bulgaria": "BG", "bulgarian": "BG",
	"liechtenstein": "LI", "liechtensteiner": "LI",
	"andorra": "AD", "andorran": "AD",
	"monaco": "MC", "monacan": "MC",
	"san marino": "SM", "sanmarino": "SM", "sammarinese": "SM",
	"vatican city": "VA", "vatican": "VA", "holy see": "VA", "vaticanstate": "VA", "pope": "VA",
	"maldives": "MV", "maldivian": "MV",
	"brunei": "BN", "bruneian": "BN",
	"rwanda": "RW", "rwandan": "RW",
	"congo": "CG", "congolese": "CG",
	"yemen": "YE", "houthi": "YE", "yemeni": "YE", "houthis": "YE",
	"libanon": "LB", "lebanese": "LB", "lebanon": "LB", "hezbollah": "LB", "beirut": "LB",
	"palestine": "PS", "palestinian": "PS", "gaza": "PS", "west bank": "PS", "hamas": "PS", "fatah": "PS",
	"iraq": "IQ", "iraqi": "IQ", "baghdad": "IQ", "saddam": "IQ", "isis": "IQ", "islamic state": "IQ",
	"oman": "OM", "omani": "OM",
	"bahrain": "BH", "bahraini": "BH",
	"syria": "SY", "syrian": "SY", "damascus": "SY", "assad": "SY",
	"cambodia": "KH", "cambodian": "KH",
	"laos": "LA", "laotian": "LA",
	"sudan": "SD", "sudanese": "SD",
}

var Emoji = map[string]string{
	"san francisco": "🌁", "sf": "🌁", "sanfrancisco": "🌁",
	"middle east": "🏜️", "middleeast": "🏜️", "middle-east": "🏜️", "mideast": "🏜️",
	"bitcoin": "💱", "btc": "💱",
	"cryptocurrency": "💱", "crypto": "💱",
	"blockchain": "🔗", "decentralized": "🔗", "web3": "🔗",
	"stablecoin": "💱", "stablecoins": "💱",
	"gold": "🟡", "silver": "⚪", "copper": "🟤",
	"oil": "🛢️", "crude oil": "🛢️", "wti": "🛢️", "brent": "🛢️",
	"natural gas": "⛽", "gas": "⛽",
	"wheat": "🌾", "corn": "🌽", "soybeans": "🫘",
	"coffee": "☕", "sugar": "🍭", "cotton": "🤍",
	"palladium": "🔩", "platinum": "🔗", "aluminum": "🪙",
	"coal": "⛏️", "iron ore": "🪨", "steel": "🔩",
	"lumber": "🪵", "timber": "🌲", "wood": "🌳",
	"rare earths": "🪨", "lithium": "🔋", "cobalt": "🔋", "rare earth": "🪨",
	"correction": "📉",
	"bullish":    "🐂", "bearish": "🐻", "bulls": "🐂", "bears": "🐻",
	"volatility": "📊", "recession": "📉", "recovery": "📈",
	"growth": "📈", "expansion": "📈", "contraction": "📉",
	"bubble": "💥", "crash": "💥", "collapse": "💥", "collapses": "💥", "crashes": "💥",
	"rally": "📈", "sell-off": "📉", "pullback": "📉", "drop": "💧",
	"surge": "📈", "spike": "📈", "plunge": "📉", "plummets": "📉",
	"dollar": "💵", "usd": "💵", "eur": "💶", "euro": "💶",
	"yen": "💴", "jpy": "💴", "pound": "💷", "gbp": "💷",
	"yuan": "💴", "cny": "💴", "rmb": "💴",
	"fed": "🏛️", "federal reserve": "🏛️", "fomc": "🏛️",
	"ecb": "🏛️", "central bank": "🏛️",
	"bank of england": "🏛️", "boe": "🏛️",
	"bank of japan": "🏛️", "boj": "🏛️",
	"people's bank of china": "🏛️", "pboc": "🏛️",
	"reserve bank of australia": "🏛️", "rba": "🏛️",
	"inflation": "📈", "cpi": "📊", "ppi": "📊",
	"gdp": "📊", "unemployment": "👷‍♂️",
	"payrolls": "📊", "retail sales": "📊", "manufacturing": "📊",
	"pmi": "📊", "jobless claims": "📉", "consumer confidence": "📊",
	"earnings": "📄", "revenue": "💰", "profit": "💰",
	"ipo": "🔔", "ipos": "🔔", "merger": "🤝", "acquisition": "🤝", "deal": "🤝",
	"partnership": "🤝", "acquire": "🤝", "acquires": "🤝",
	"drops": "💦", "decline": "📉", "declines": "📉",
	"aircraft": "✈️", "aircrafts": "✈️",
	"opa":      "🛍️",
	"video":    "📹",
	"bankrupt": "💔",
	"reports":  "📄", "report": "📄",
	"secures":   "🔒",
	"quarterly": "📅", "quarter": "📅", "annual": "📅", "yearly": "📅",
	"emission": "🌱", "emissions": "🌱", "carbon": "🌱", "footprint": "🌱",
	"uranium":                 "☢️",
	"initial public offering": "🔔",
	"treasury":                "🏛️", "yield": "📊", "bonds": "💳", "portfolio": "💼",
	"stocks": "📈", "shares": "📈", "dividend": "💰",
	"rate hike": "📈", "rate cut": "📉",
	"lawyer": "👨‍⚖️", "legal": "👨‍⚖️", "litigation": "👨‍⚖️",
	"regulation": "📜", "compliance": "📜", "antitrust": "📜",
	"bankruptcy": "💔", "insolvency": "💔", "restructuring": "🔄",
	"fraud": "🚨", "scam": "🚨", "scandal": "🚨",
	"investigation": "🔍", "probe": "🔍", "audit": "🔍",
	"lawsuit": "👨‍⚖️", "class action": "👨‍⚖️",
	"tax": "💰", "taxation": "💰", "tax cut": "📉", "tax hike": "📈",
	"insider": "🚨",
	"losing":  "😢", "loser": "😢", "loses": "😢",
	"cheap": "💸", "cheap stock": "💸", "bargain": "💸",
	"expensive": "💰", "overpriced": "💰", "premium": "💰",
	"tariff": "🚫", "trade": "🌐",
	"sleep": "🛌", "sleeping": "🛌", "sleepy": "😴", "snooze": "😴",
	"transcript": "📜", "earnings call": "📞",
	"rating": "⭐", "downgrade": "📉", "upgrade": "📈",
	"ratings": "⭐", "downgraded": "📉", "upgraded": "📈",
	"sue": "👨‍⚖️", "litigate": "👨‍⚖️", "court": "👨‍⚖️",
	"rallies": "📈", "rallying": "📈",
	"workforce": "👷", "labor": "👷", "union": "👷", "strike": "💥", "strikes": "💥",
	"banks": "🏦", "banking": "🏦", "financial": "🏦", "bank": "🏦",
	"step down": "👣", "resign": "👋", "resignation": "👋",
	"steps down": "👣", "stepping down": "👣", "resigns": "👋", "resigning": "👋",
	"wall street": "🏙️", "wallstreet": "🏙️", "ws": "🏙️",
	"nyse": "🗽", "new york stock exchange": "🗽", "new york": "🗽",
	"chart": "📊", "charts": "📊", "graph": "📈", "trend": "📈", "trends": "📈",
	"downturn": "📉", "downturns": "📉",
	"bonus": "🎁", "bonuses": "🎁", "incentive": "🎁", "incentives": "🎁",
	"baseball": "⚾", "basketball": "🏀", "nfl": "🏈", "soccer": "⚽", "hockey": "🏒",
	"export": "📦", "import": "📦",
	"exports": "📦", "imports": "📦",
	"shipment": "🚚", "shipments": "🚚", "delivery": "📦", "deliveries": "📦",
	"calendar": "📅", "calendars": "📅",
	"schedule": "📅", "schedules": "📅",
	"bet": "♠️", "betting": "♠️",
	"grow": "📈", "grows": "📈",
	"hotel": "🏨", "hotels": "🏨", "hospitality": "🏨",
	"restaurant": "🍽️", "restaurants": "🍽️", "food": "🍽️",
	"franchise": "🏪", "franchises": "🏪",
	"retail": "🏬", "retailer": "🏬", "retailers": "🏬",
	"e-commerce": "🛒", "online shopping": "🛒", "ecommerce": "🛒",
	"consumer": "🛍️", "consumers": "🛍️",
	"intel":       "💻",
	"residential": "🏠", "real estate": "🏠", "housing": "🏠",
	"resort": "🏖️", "resorts": "🏖️", "vacation": "🏖️", "vacations": "🏖️",
	"travel": "✈️", "travels": "✈️", "tourism": "🌍", "tourist": "🌍",
	"airline": "✈️", "airlines": "✈️", "aviation": "✈️",
	"holiday": "🎉", "holidays": "🎉",
	"discount": "💸", "discounts": "💸", "sale": "💸", "sales": "💸",
	"evs": "🚗", "vehicles": "🚗", "car": "🚗", "cars": "🚗",
	"pipeline": "🚧", "pipelines": "🚧",
	"refinery": "🏭", "refineries": "🏭",
	"factory": "🏭", "factories": "🏭",
	"sells": "💸", "sell": "💸", "selling": "💸",
	"gamble": "🎲", "gambling": "🎲", "casino": "🎰", "casinos": "🎰",
	"mover": "📈", "movers": "📈", "move": "📈", "moving": "📈",
	"acquisitions": "🤝", "acquiring": "🤝",
	"thread": "🧵", "threads": "🧵", "threaded": "🧵",
	"shadow": "🌑", "shadows": "🌑", "shadowed": "🌑",
	"dangerous": "⚠️", "danger": "⚠️",
	"breakthrough": "🔬",
	"fusion":       "⚡️",
	"quantum":      "💻",
	"aws":          "☁️", "web services": "☁️",
	"artificial intelligence": "🤖", "ai": "🤖", "machine learning": "🤖",
	"gene therapy": "🧬", "genetics": "🧬", "biotech": "🧬", "biotechnology": "🧬",
	"medical breakthrough": "💊", "pharmaceutical": "💊",
	"battery": "🔋", "energy storage": "🔋",
	"solar": "☀️", "solar power": "☀️", "renewable energy": "☀️",
	"autonomous": "🚗", "self-driving": "🚗", "autonomous vehicle": "🚗", "ev": "🚗",
	"robotics": "🤖", "automation": "🤖",
	"semiconductor": "💻", "chip": "💻", "processor": "💻",
	"space": "🚀", "satellite": "🛰️", "aerospace": "✈️",
	"telecommunications": "📡", "5g": "📡", "6g": "📡",
	"data breach":     "🔒",
	"cloud computing": "☁️", "cloud": "☁️", "saas": "☁️",
	"data":    "📊",
	"console": "🎮", "gaming": "🎮", "game": "🎮",
	"xbox": "🎮", "playstation": "🎮", "nintendo": "🎮",
	"virtual reality": "🕶️", "vr": "🕶️", "augmented reality": "🕶️", "ar": "🕶️",
	"apple": "🍏", "amazon": "📦",
	"silicon valley": "🏞️", "tech hub": "🏞️", "innovation": "💡",
	"silicon": "💻", "chips": "💻",
	"pharma": "💊", "pharmaceuticals": "💊", "drug": "💊",
	"energy": "⚡️", "oil and gas": "🛢️",
	"medical": "💊", "healthcare": "💊", "health tech": "💊",
	"medicine": "💊",
	"water":    "💧",
	"rockets":  "🚀", "rocket": "🚀",
	"infrastructure": "🏗️", "construction": "🏗️", "engineering": "🏗️",
	"electricity": "⚡️", "power grid": "⚡️", "smart grid": "⚡️",
	"telecom": "📡", "telecoms": "📡", "electric": "⚡️",
	"logistics": "🚚", "supply chain": "🚚",
	"temperature": "🌡️", "climate": "🌍", "temperatures": "🌡️",
	"sustainability": "🌱", "green energy": "🌱",
	"chemistry": "🧪", "chemical": "🧪", "chemicals": "🧪",
	"labs": "🔬", "laboratories": "🔬", "lab": "🔬",
	"minerals": "⛏️", "mining": "⛏️", "ore": "⛏️", "mineral": "⛏️",
	"biomedical": "💊",
	"gpu":        "💻", "cpu": "💻", "gpus": "💻",
	"tv": "📺", "television": "📺",
	"strategy": "♟️", "strategic": "♟️",
	"institutional": "🐳", "whale": "🐳", "whales": "🐳", "hedge fund": "🐳", "asset manager": "🐳", "fund": "🐳",
	"engine": "🏎️", "race": "🏎️", "races": "🏎️", "motor": "🏎️",
	"meta": "🌀", "metaverse": "🌀",
	"bull": "🐂", "bear": "🐻",
	"industrial": "🏭", "industrials": "🏭",
	"yields": "📊",
	"openai": "🤖", "chatgpt": "🤖", "gpt": "🤖",
	"google": "🔍", "alphabet": "🔍", "search engine": "🔍",
	"nvidia":    "💻",
	"microsoft": "💻", "msft": "💻", "windows": "💻",
	"linux": "🐧", "ubuntu": "🐧", "red hat": "🐧",
	"release": "📦", "releases": "📦", "update": "🔄", "updates": "🔄",
	"researcher": "🔬", "research": "🔬", "scientist": "🔬",
	"software":  "💻",
	"developer": "💻", "dev": "💻", "programmer": "💻", "coding": "💻",
	"app": "📱", "application": "📱", "apps": "📱",
	"mobile":     "📱",
	"developers": "💻", "programmers": "💻",
	"layoffs": "📉", "layoff": "📉", "job cuts": "📉", "job cut": "📉",
	"robot": "🤖", "robots": "🤖",
	"robotaxi": "🤖", "robotaxis": "🤖",
	"defense": "🛡️", "defence": "🛡️", "military": "🪖",
	"defense contract": "🛡️", "military contract": "🛡️", "arms deal": "🛡️",
	"defense spending": "🛡️", "military spending": "🛡️", "pentagon": "🛡️",
	"weapons": "🛡️", "weapons system": "🛡️", "missile": "🛡️",
	"fighter jet": "🛩️", "military aircraft": "🛩️", "helicopter": "🚁",
	"naval": "⚓", "submarine": "⚓", "warship": "⚓",
	"cybersecurity": "🔒", "cyber defense": "🔒", "cyber attack": "🔓",
	"cyberattack": "🔓", "cyberattacks": "🔓",
	"national security": "🛡️", "homeland security": "🛡️",
	"nato": "🧭", "alliance": "🧭",
	"conflict": "⚔️", "war": "⚔️", "tension": "⚔️",
	"nuclear":      "☢️",
	"peacekeeping": "🕊️", "ceasefire": "🕊️",
	"whistle": "📢", "whistleblower": "📢", "leak": "📢", "whistleblowers": "📢",
	"espionage": "🕵️", "spy": "🕵️", "intelligence": "🕵️",
	"sanctions": "🚫", "embargo": "🚫", "trade war": "🚫",
	"humanitarian": "🤝", "relief": "🤝",
	"army": "🪖", "navy": "⚓", "air force": "✈️",
	"space force": "🚀", "coast guard": "🚢",
	"laser": "🔫", "drones": "🛸", "unmanned": "🛸", "dron": "🛸",
	"secret": "🤫", "classified": "🤫", "top secret": "🤫",
	"vulnerability": "🛡️", "vulnerabilities": "🛡️",
	"security": "🔒", "secure": "🔒", "safety": "🦺",
	"threat": "⚠️", "threats": "⚠️", "risks": "⚠️",
	"attacks": "⚔️", "attack": "⚔️",
	"malicious": "🦠", "malware": "🦠", "virus": "🦠", "hacker": "🕵️",
	"hacked": "🔓", "hacking": "🔓", "breach": "🔓", "breached": "🔓",
	"vulnerable": "🛡️",
	"cisa":       "🇺🇸",
	"exploit":    "🛡️", "exploits": "🛡️", "exploitations": "🛡️",
	"risk":   "⚠️",
	"police": "👮", "law enforcement": "👮", "security forces": "👮",
	"officer": "👮", "officers": "👮",
	"web":      "🕸️",
	"internet": "🌐", "online": "🌐",
	"downgrades": "📉", "upgrades": "📈",
	"job market": "👷", "employment": "👷", "hiring": "👷", "jobs": "👷",
	"lunch": "🍽️", "lunches": "🍽️", "dinner": "🍽️", "dinners": "🍽️",
	"breakfast": "🍽️", "breakfasts": "🍽️", "meal": "🍽️", "meals": "🍽️",
	"computer": "💻", "computers": "💻", "pc": "💻", "laptop": "💻",
	"macro": "🌍", "macroeconomics": "🌍", "macroeconomic": "🌍",
	"employee": "👷", "employees": "👷",
	"startup": "🚀", "startups": "🚀", "start-up": "🚀",
	"cash": "💵", "liquidity": "💵",
	"job":     "👷",
	"listing": "📄", "listings": "📄", "listed": "📄",
	"close": "🚪", "closes": "🚪", "closing": "🚪",
	"tariffs": "🚫",
	"bill":    "📜", "bills": "📜", "legislation": "📜", "law": "📜",
	"strong": "💪", "strength": "💪", "stronger": "💪", "strongest": "💪",
	"weak": "💔", "weaker": "💔", "weakness": "💔", "weakest": "💔",
	"vaccine": "💉", "vaccines": "💉",
	"kitchen": "🍽️",
	"penny":   "🪙", "pennies": "🪙", "cent": "🪙", "cents": "🪙",
	"record":    "🏅",
	"insurance": "🛡️", "insurer": "🛡️", "insurers": "🛡️",
	"looks": "👀", "looking": "👀", "look": "👀",
	"see": "👀", "sees": "👀", "seen": "👀",
	"risky": "⚠️", "riskier": "⚠️", "riskiest": "⚠️",
	"safe":      "🦺",
	"all-world": "🌍", "worldwide": "🌍", "global": "🌍", "international": "🌍",
	"diamond": "💎", "diamonds": "💎", "gem": "💎", "gems": "💎",
	"farming": "🚜", "agriculture": "🚜", "farmer": "🚜", "farmers": "🚜", "farm": "🚜",
	"phising": "🎣", "fishing": "🎣", "fish": "🎣",
	"chain": "🔗", "chains": "🔗",
	"troop": "🪖", "troops": "🪖",
	"nyc": "🗽", "new york city": "🗽", "newyork": "🗽",
	"green": "🌱", "sustainable": "🌱",
	"metal": "⛏️", "metals": "⛏️", "metallic": "⛏️",
	"meme": "🖼️", "memes": "🖼️", "viral": "🖼️",
	"bioscience": "🧬",
	"disease":    "🦠", "diseases": "🦠", "illness": "🦠", "illnesses": "🦠",
	"death": "💀", "deaths": "💀", "fatality": "💀", "fatalities": "💀",
	"dead": "💀", "dying": "💀", "died": "💀",
	"study": "📚", "studies": "📚",
	"student": "🎓", "students": "🎓", "education": "🎓", "school": "🎓",
	"university": "🎓", "college": "🎓", "campus": "🎓",
	"opec":    "🛢️",
	"goodbye": "👋", "bye": "👋", "farewell": "👋",
	"hello": "👋", "hi": "👋", "greetings": "👋", "welcome": "👋",
	"call":       "📞",
	"prediction": "🔮", "forecast": "🔮", "outlook": "🔮", "predicts": "🔮",
	"food service": "🍽️",
	"breaches":     "🔓",
	"analytics":    "📊",
	"baltic":       "🌊", "baltics": "🌊", "eastern europe": "🌍", "balkans": "🌍",
	"arctic": "🧊", "antarctic": "🧊", "polar": "🧊",
	"indo-pacific": "🌊", "asia-pacific": "🌊", "south china sea": "🌊",
	"mediterranean": "🌊", "strait": "🌊", "straits": "🌊",
	"united nations": "🕊️", "un": "🕊️", "security council": "🕊️", "unsc": "🕊️",
	"g7": "🤝", "g20": "🤝", "g8": "🤝",
	"oecd": "🏛️", "wto": "🏛️", "imf": "🏛️", "world bank": "🏛️",
	"asean": "🤝", "aukus": "🤝", "quad": "🤝", "five eyes": "👁️",
	"osce": "🤝", "arab league": "🤝", "african union": "🌍",
	"sco": "🤝", "csto": "🤝",
	"iaea": "☢️", "opcw": "🧪", "icj": "⚖️", "icc": "⚖️",
	"health": "🏥",
	"cia":    "🕵️", "fbi": "🔍", "nsa": "📡", "dhs": "🏛️",
	"state department": "🏛️", "dod": "🛡️",
	"commerce": "💼", "justice": "⚖️",
	"homeland": "🏛️", "veterans": "🎖️", "energy department": "⚡️",
	"mi5": "🕵️", "mi6": "🕵️", "gchq": "📡", "mod": "🛡️",
	"mossad": "🕵️", "shin bet": "🕵️", "aman": "🕵️",
	"fsb": "🕵️", "gru": "🕵️", "svr": "🕵️",
	"mss": "🕵️", "pla": "🪖",
	"doctrine": "📋", "tactics": "🎯",
	"deployment": "🚀", "operations": "⚔️", "mission": "🎯", "campaign": "⚔️",
	"theater": "🗺️", "front": "⚔️", "battlefield": "⚔️", "warzone": "⚔️",
	"command": "⭐", "headquarters": "🏛️", "base": "🏕️", "garrison": "🏕️",
	"regiment": "🪖", "battalion": "🪖", "brigade": "🪖", "division": "🪖",
	"special forces": "🥷", "special ops": "🥷", "commandos": "🥷",
	"reconnaissance": "👁️", "surveillance": "👁️", "patrol": "👁️",
	"maneuvers": "🚛", "exercises": "🏋️", "drills": "⛏️", "training": "🏋️",
	"mobilization": "🚛", "reserves": "🪖", "conscription": "🪖", "draft": "🪖",
	"readiness": "⚡️", "alert": "🚨", "defcon": "🚨", "threat level": "🚨",
	"armament": "🔫", "arsenal": "🔫", "stockpile": "📦", "inventory": "📋",
	"ammunition": "💥", "ordnance": "💥", "explosives": "💥", "munitions": "💥",
	"ballistic": "🚀", "cruise missile": "🚀", "icbm": "🚀", "hypersonic": "⚡️",
	"stealth": "👻", "radar": "📡", "sonar": "📡", "jamming": "📡",
	"fortress": "🏰", "bunker": "🏠", "fortification": "🏰", "perimeter": "🔒",
	"diplomacy": "🤝", "diplomatic": "🤝", "ambassador": "🎩", "embassy": "🏛️",
	"consulate": "🏛️", "envoy": "🎩", "delegation": "👥", "summit": "🏔️",
	"treaty": "📜", "agreement": "📋", "accord": "📋", "pact": "🤝",
	"memorandum": "📝", "protocol": "📋", "convention": "📋", "charter": "📜",
	"negotiations": "💬", "talks": "💬", "dialogue": "💬", "mediation": "⚖️",
	"bilateral": "🤝", "multilateral": "👥", "unilateral": "☝️",
	"sovereignty": "👑", "territorial": "🗺️", "border": "🚧", "boundary": "🚧",
	"blockade": "🚫", "isolation": "🏝️",
	"deterrence": "🛡️", "containment": "📦", "appeasement": "🕊️",
	"sphere of influence": "🌐", "proxy": "🎭", "client state": "🎭",
	"soft power": "🎭", "hard power": "💪", "smart power": "🧠",
	"realpolitik": "♟️", "geostrategy": "♟️", "rebalancing": "⚖️",
	"think tank": "🧠", "analysis": "📊", "assessment": "📋", "briefing": "📋",
	"findings":   "🔍",
	"projection": "📈", "scenario": "🎬", "modeling": "📊",
	"policy": "📋", "recommendation": "💡", "proposal": "📝", "framework": "🏗️",
	"white paper": "📄", "blue book": "📘", "green paper": "📗",
	"declassified": "📂", "confidential": "🤫",
	"source": "📡",
	"expert": "🎓", "analyst": "📊", "scholar": "🎓", "advisor": "💼",
	"escalation": "📈", "de-escalation": "📉", "crisis": "🚨",
	"standoff": "⚔️", "confrontation": "⚔️", "hostilities": "⚔️",
	"truce": "🕊️", "armistice": "📜", "peace": "🕊️", "resolution": "✅",
	"intervention": "🚁", "refugee": "🏃",
	"insurgency": "⚔️", "rebellion": "✊", "uprising": "✊", "revolt": "✊",
	"terrorism": "💥", "terrorist": "💥", "extremism": "⚠️", "radicalization": "⚠️",
	"asymmetric": "⚖️", "guerrilla": "🥷", "hybrid warfare": "🎭", "information war": "📺",
	"propaganda": "📢", "disinformation": "🚫", "psyops": "🧠", "influence": "🎭",
	"cyber warfare": "💻", "cyber domain": "💻", "digital": "💻", "electronic": "📡",
	"satellites": "🛰️", "space warfare": "🚀", "anti-satellite": "💥",
	"autonomous weapons": "🤖", "lethal autonomous": "🤖",
	"quantum computing": "⚛️", "encryption": "🔐", "cryptography": "🔐",
	"biometrics": "👁️", "facial recognition": "👁️", "surveillance state": "👁️",
	"critical infrastructure": "🏗️", "resilience": "💪",
	"economic warfare": "💰", "quotas": "📊",
	"strategic resources": "💎",
	"food security":       "🌾", "water security": "💧", "supply security": "🔗",
	"sanctions regime": "🚫", "export controls": "📦", "technology transfer": "🔄",
	"dual-use": "⚖️", "sensitive technology": "🔒", "export licensing": "📋",
	"institute": "🏛️", "foundation": "🏛️", "center": "🏛️",
	"council": "🏛️", "organization": "🏛️", "think": "🧠",
	"fellowship": "🎓", "strategic studies": "♟️", "foreign policy": "🌍",
	"defense studies": "🛡️", "security studies": "🔐", "international relations": "🌐",
	"geopolitics": "🗺️", "intelligence studies": "🕵️", "nuclear studies": "⚛️",
	"arms control": "🤝", "non-proliferation": "🚫", "verification": "✅",
	"brookings": "🏛️", "csis": "🏛️", "rand": "🏛️", "heritage": "🏛️",
	"carnegie": "🏛️", "atlantic council": "🏛️", "cfr": "🏛️", "chatham house": "🏛️",
	"slbm": "🚀", "irbm": "🚀", "srbm": "🚀",
	"missile defense": "🛡️", "interceptor": "🛡️", "patriot": "🛡️", "thaad": "🛡️",
	"iron dome": "🛡️", "aegis": "🛡️",
	"drone": "🛸", "uav": "🛸", "ucav": "🛸", "loitering munition": "🛸",
	"predator": "🛸", "reaper": "🛸", "global hawk": "🛸", "switchblade": "🛸",
	"f-22": "✈️", "f-35": "✈️", "b-21": "✈️", "su-57": "✈️", "b-2": "💣",
	"bomber": "💣", "awacs": "📡",
	"apache": "🚁", "chinook": "🚁", "blackhawk": "🚁",
	"tank": "🚗", "armored vehicle": "🚗", "ifv": "🚗", "apc": "🚗",
	"artillery": "💥", "howitzer": "💥", "mortar": "💥", "mlrs": "🚀",
	"naval vessel": "⚓", "aircraft carrier": "🚢", "destroyer": "⚓",
	"nuclear submarine": "⚛️", "frigate": "⚓", "corvette": "⚓", "patrol boat": "🚤",
	"deep learning":   "🧠",
	"neural networks": "🧠", "computer vision": "👁️", "natural language": "🗣️",
	"unmanned systems": "🤖", "swarm": "🐝",
	"nanotechnology": "🔬", "materials science": "🧪", "composites": "🧪",
	"superconductors": "⚡️", "metamaterials": "🔬", "graphene": "🧪",
	"photonics": "💡", "directed energy": "⚡️", "railgun": "⚡️",
	"electromagnetic": "⚡️", "emp": "⚡️", "electronic warfare": "📡",
	"spoofing": "🎭", "signals": "📡", "sigint": "📡", "elint": "📡",
	"quantum radar": "📡", "quantum communication": "📡",
	"cbrn": "☣️", "biological": "🦠",
	"radiological": "☢️", "wmd": "☢️", "proliferation": "🔄",
	"control": "🎮", "c2": "🎮", "c4isr": "📡",
	"domain": "🌐", "multi-domain": "🌐",
	"joint operations": "🤝", "combined": "🤝", "coalition": "🤝",
	"interoperability": "🔄", "standardization": "📏",
	"operational":      "⚙️",
	"maintenance":      "🔧",
	"force projection": "💪",
	"preemption":       "⚡️", "prevention": "🚫",
	"humint": "🕵️", "geoint": "🗺️", "masint": "🔬", "osint": "📰",
	"counterintelligence": "🛡️", "covert": "🥷", "clandestine": "🥷",
	"black ops": "🥷", "special operations": "💀",
	"psywar": "🧠", "miso": "📢", "opsec": "🔒", "comsec": "🔐",
	"classification": "🔒", "compartmented": "📁", "need to know": "👁️",
	"clearance": "✅", "vetting": "🔍", "background check": "📋",
	"conventional": "⚔️", "unconventional": "🥷", "irregular": "🌀",
	"proxy war": "🎭", "shadow war": "🌑", "gray zone": "🌫️", "ambiguous": "❓",
	"amphibious": "🌊", "airborne": "🪂", "air assault": "🚁", "urban warfare": "🏙️",
	"mountain warfare": "⛰️", "desert warfare": "🏜️", "arctic warfare": "🧊",
	"anti-access": "🚫", "area denial": "🚫", "a2/ad": "🚫",
	"superpower": "💪", "great power": "💪", "middle power": "⚖️", "regional power": "🗺️",
	"hegemon": "👑", "balance of power": "⚖️", "power vacuum": "🕳️",
	"pivot": "🔄", "rebalance": "⚖️", "engagement": "🤝",
	"isolationism": "🏝️",
	"entente":      "🤝",
	"ratification": "✅", "withdrawal": "🚪", "suspension": "⏸️", "violation": "⚠️",
	"persian gulf": "🌊",
	"sahel":        "🏜️",
	"caucasus":     "⛰️", "horn of africa": "🌍", "maghreb": "🌍",
	"levant": "🗺️", "gulf states": "⛽",
	"semiconductors": "💾",
	"broadband":      "📡", "fiber optic": "💡",
	"tech transfer": "🔄", "ip theft": "🚫", "decoupling": "✂️",
	"reshoring": "🏭", "friend-shoring": "🤝", "nearshoring": "📍", "onshoring": "🏠",
	"critical minerals": "💎", "strategic stockpile": "📦", "export ban": "🚫",
	"conference": "🏛️", "summitry": "🏔️",
	"debt":    "💳",
	"rebound": "🏀", "bounce": "🏀",
	"contract": "📄", "contracts": "📄",
	"politic": "👞", "politics": "👞", "political": "👞",
	"boat": "🚤", "boats": "🚤", "ship": "🚢", "ships": "🚢",
	"flight": "✈️", "flights": "✈️",
	"llm": "🤖", "llms": "🤖", "agi": "🤖",
	"cannabis": "🍁",
	"fixed":    "🔧",
	"explode":  "💥", "explosion": "💥", "explosions": "💥", "explodes": "💥",
	"bomb": "💣", "bombs": "💣", "detonate": "💥", "detonates": "💥",
	"missiles": "🚀",
	"test":     "🧪", "tests": "🧪", "testing": "🧪", "tested": "🧪",
	"interview": "🎤", "interviews": "🎤", "interviewing": "🎤", "interviewed": "🎤",
	"podcast": "🎙️", "podcasts": "🎙️", "broadcast": "📡", "broadcasts": "📡",
	"live": "📺", "streaming": "📺", "stream": "📺",
	"calls": "📞", "puts": "📉",
	"hidden":   "👻",
	"positive": "👍", "negatives": "👎", "negative": "👎",
	"comeback": "🔙",
	"network":  "🌐", "networks": "🌐", "networking": "🌐",
	"conflicts": "⚔️", "wars": "⚔️",
	"caribbean": "🌴",
	"eyes":      "👁️", "watching": "👀", "watch": "👀",
	"women": "💁‍♀️", "woman": "💁‍♀️",
	"flag": "⛳️", "flags": "⛳️", "banner": "⛳️", "banners": "⛳️",
	"funding": "💰", "funds": "💰",
	"hedge":  "🐳",
	"eye":    "👁️",
	"home":   "🏠",
	"lowest": "🔽", "highest": "🔼", "high": "🔼", "low": "🔽",
	"top": "🔝", "bottom": "🔚", "peak": "🏔️", "trough": "🌊",
	"billionaire": "💰", "billionaires": "💰", "millionaire": "💰", "millionaires": "💰",
	"telegram": "📱", "whatsapp": "📱", "signal": "📱", "messenger": "📱",
	"unveil": "🎭", "unveils": "🎭", "reveal": "🎭", "reveals": "🎭",
	"fire": "🔥", "fires": "🔥", "burn": "🔥", "burns": "🔥",
	"palantir": "🔮",
	"bid":      "♦️", "bids": "♦️", "bidding": "♦️", "bidder": "♦️", "bidders": "♦️",
	"offer": "💌", "offers": "💌", "offering": "💌", "offerings": "💌",
	"warfare": "⚔️",
	"realty":  "🏢",
	"reit":    "🏢",
	"future":  "🔮", "futures": "🔮",
	"blueprint": "📐", "blueprints": "📐", "plan": "📐", "plans": "📐",
	"strategies":  "♟️",
	"tactical":    "🎯",
	"stagflation": "📉", "depression": "📉",
	"economy": "👨‍🏫", "economies": "👨‍🏫", "economic": "👨‍🏫", "economist": "👨‍🏫", "economists": "👨‍🏫",
	"chair": "🪑", "chairs": "🪑", "chairman": "🪑", "chairwoman": "🪑", "chairperson": "🪑",
	"ceo": "👔", "cfo": "👔", "coo": "👔", "cto": "👔", "executive": "👔",
	"acquired":    "🤝",
	"drugs":       "💊",
	"assassinate": "🔫", "assassination": "🔫", "assassin": "🔫", "assassinates": "🔫",
	"launder": "🧼", "laundering": "🧼",
	"charged": "⚖️", "charges": "⚖️", "charging": "⚖️",
	"arrested": "🚔", "arrests": "🚔", "arresting": "🚔", "arrest": "🚔",
	"corruption": "💰", "corrupt": "💰", "bribery": "💰", "bribe": "💰",
	"a.i.":        "🤖",
	"mathematics": "🧮", "math": "🧮", "mathematical": "🧮",
	"storm": "🌩️", "storms": "🌩️", "stormy": "🌩️", "hurricane": "🌀", "hurricanes": "🌀",
	"knife": "🔪", "knives": "🔪", "stab": "🔪", "stabbing": "🔪",
	"dream": "💭", "dreams": "💭", "dreaming": "💭", "dreamed": "💭",
	"festival": "🎉", "festivals": "🎉", "celebration": "🎊", "celebrations": "🎊",
	"target": "🎯", "targets": "🎯", "targeting": "🎯", "targeted": "🎯",
	"cryptocurrencies": "💱", "crude": "🛢️",
	"bombers": "💣", "bombing": "💣", "bombings": "💣",
	"freed": "⛓️‍💥",
	"brics": "🧱", "bric": "🧱",
	"boring": "😴",
	"reward": "🏆", "rewards": "🏆", "rewarding": "🏆",
	"value investing": "👨‍🏫",
	"plays":           "🎮", "play": "🎮",
	"megathread": "🧵",
	"cut":        "✂️", "cuts": "✂️", "cutting": "✂️", "cutoff": "✂️",
	"dark": "🌑", "darkness": "🌑", "shadowy": "🌑", "shady": "🌑",
	"light": "💡", "bright": "💡", "brightness": "💡",
	"king": "👑", "queen": "👑", "royal": "👑", "monarch": "👑",
	"neuroscience": "🧠", "brain": "🧠", "cognitive": "🧠",
	"etf":     "🗂️",
	"burning": "🔥", "burned": "🔥",
	"therapeutics": "💊", "therapy": "💊", "therapeutic": "💊",
	"human rights": "🕊️",
	"videos":       "📹", "film": "🎥", "films": "🎥",
	"disney": "🏰", "disneyland": "🏰", "disneyworld": "🏰",
	"netflix": "📺", "hbo": "📺",
	"retirement": "🏖️",
	"retire":     "🏖️", "retired": "🏖️", "retires": "🏖️",
	"competition": "🏆", "competitive": "🏆", "compete": "🏆", "competes": "🏆",
	"repurchase": "🔄", "repurchases": "🔄", "buyback": "🔄", "buybacks": "🔄",
	"wildfire": "🔥", "wildfires": "🔥",
	"shipping": "🚢", "shippings": "🚢",
	"misinformation": "🚫", "news": "📰",
	"moves":    "🚶",
	"genocide": "🩸",
	"loan":     "💳", "loans": "💳", "lending": "💳", "lend": "💳",
	"luxury": "💎", "luxuries": "💎", "luxurious": "💎",
	"killed": "💀", "killing": "💀", "kills": "💀",
	"emergent": "🌱", "emerging": "🌱", "emergence": "🌱", "emergents": "🌱",
	"question": "❓", "questions": "❓", "questioning": "❓", "questioned": "❓",
	"winner": "🏆", "winners": "🏆", "winning": "🏆", "wins": "🏆", "win": "🏆",
	"riding": "🚴", "rides": "🚴", "ride": "🚴",
	"toy": "🧸", "toys": "🧸",
	"latest":     "🆕",
	"undervalue": "⚖️", "undervalued": "⚖️", "overvalue": "⚖️", "overvalued": "⚖️",
	"blacklist": "🚫", "blacklists": "🚫", "blacklisted": "🚫", "blacklisting": "🚫",
	"bets":    "♠️",
	"price":   "🏷️",
	"survive": "🛟", "survives": "🛟", "surviving": "🛟", "survived": "🛟",
	"rescue": "🛟", "rescues": "🛟", "rescuing": "🛟", "rescued": "🛟",
	"asia": "🌏",
	"apac": "🌏",
	"ban":  "🚫", "bans": "🚫", "banning": "🚫", "banned": "🚫",
	"talk": "💬", "discuss": "💬", "discusses": "💬", "discussing": "💬",
	"escalate": "🧗", "escalates": "🧗", "escalating": "🧗", "escalated": "🧗",
	"spies": "🕵️", "spying": "🕵️", "spied": "🕵️",
	"cool": "🥶", "cooling": "🥶", "cooler": "🥶",
	"hot": "🔥", "heat": "🔥", "heating": "🔥", "hotter": "🔥",
	"hell": "🔥", "heaven": "☁️", "paradise": "🌴", "utopia": "🏝️",
	"cold": "❄️", "freezing": "❄️", "frozen": "❄️",
	"warm": "🌡️", "warming": "🌡️",
	"doctor": "👨‍⚕️", "doctors": "👨‍⚕️",
	"?":      "❓",
	"bought": "🛒", "buy": "🛒", "buys": "🛒", "buying": "🛒",
	"crashed": "💥", "crashing": "💥",
	"tesla": "🚗", "tsla": "🚗",
	"trading": "📈", "trades": "📈", "trader": "📈", "traders": "📈",
	"posted": "📬", "posts": "📬", "posting": "📬", "post": "📬",
	"diversification": "🌈", "diversify": "🌈", "diversified": "🌈",
	"run": "🏃", "runs": "🏃", "running": "🏃", "ran": "🏃",
	"batteries": "🔋",
	"hardware":  "💻", "tech": "💻", "technology": "💻",
	"founder": "👨‍💼", "founders": "👨‍💼", "founding": "👨‍💼",
	"power": "⚡️️", "powers": "⚡️️", "powered": "⚡️️", "powering": "⚡️️",
	"seizure": "🚨", "seizures": "🚨", "seizing": "🚨", "seized": "🚨",
	"scary": "👻", "scare": "👻", "scares": "👻", "scaring": "👻",
	"fear": "👻", "fears": "👻", "fearing": "👻", "feared": "👻",
	"scams":   "🚫",
	"bond":    "💳",
	"records": "📜", "recorded": "📜", "recording": "📜",
	"mortages": "🏠", "mortgage": "🏠",
	"bell": "🔔", "bells": "🔔",
	"thinks": "🧠", "thinking": "🧠", "thought": "🧠", "thoughts": "🧠",
	"launch": "🚀", "launches": "🚀", "launched": "🚀", "launching": "🚀",
	"tsmc":   "💻",
	"raises": "🏋️‍♀️", "raise": "🏋️‍♀️", "raising": "🏋️‍♀️", "raised": "🏋️‍♀️",
	"thanks": "🙂", "thank": "🙂", "thanked": "🙂", "thanking": "🙂",
	"marine": "⚓️", "marines": "⚓️",
	"navies": "⚓️",
	"armies": "🪖",
	"review": "🔍", "reviews": "🔍", "reviewing": "🔍", "reviewed": "🔍",
	"love": "❤️", "loves": "❤️", "loving": "❤️", "loved": "❤️",
	"hate": "💔", "hates": "💔",
	"hit": "💥", "hits": "💥", "hitting": "💥",
	"broken": "🛠️", "breaks": "🛠️", "breaking": "🛠️", "broke": "🛠️", "break": "🛠️",
	"help": "🆘", "helps": "🆘", "helping": "🆘", "helped": "🆘",
	"sea": "🌊", "seas": "🌊", "ocean": "🌊", "oceans": "🌊",
	"moon": "🌛", "moons": "🌛", "lunar": "🌛",
	"driver": "🚗", "drivers": "🚗", "driving": "🚗", "drove": "🚗",
	"investigations": "🔍", "investigate": "🔍", "investigating": "🔍",
	"trash": "🗑️", "garbage": "🗑️", "waste": "🗑️", "rubbish": "🗑️",
	"score": "🏅", "scores": "🏅", "scoring": "🏅", "scored": "🏅",
	"hesitate": "❓", "hesitates": "❓", "hesitating": "❓", "hesitated": "❓",
	"investor": "💼", "investors": "💼", "investment": "💼", "investments": "💼",
	"stock":     "💼",
	"investing": "💸", "invested": "💸", "invest": "💸",
	"inside": "🕵️",
	"alpha":  "🔼", "alphas": "🔼",
	"work": "👷", "works": "👷", "working": "👷", "worked": "👷",
	"idea": "💡", "ideas": "💡",
	"reddit": "👾", "subreddit": "👾", "subreddits": "👾",
	"mad": "😡", "angry": "😡", "anger": "😡",
	"success": "🏆", "successful": "🏆", "succeed": "🏆", "succeeds": "🏆", "succeeded": "🏆",
	"africa": "🌍", "african": "🌍",
	"sports": "⚽", "sport": "⚽", "athletics": "🏃", "athlete": "🏃",
	"open": "🗃️", "opens": "🗃️", "opening": "🗃️", "opened": "🗃️",
	"file": "📂", "files": "📂", "filing": "📂", "filed": "📂",
	"gain": "📈", "gains": "📈", "gaining": "📈", "gained": "📈",
	"loss": "📉", "losses": "📉",
	"drill": "⛏️", "drilling": "⛏️", "drilled": "⛏️",
	"talking": "💬", "talked": "💬",
	"bots": "🤖", "bot": "🤖",
	"learn": "📚", "learns": "📚", "learning": "📚", "learned": "📚",
	"government": "🏛️", "governments": "🏛️", "governmental": "🏛️",
	"known": "👁️", "knows": "👁️", "knowing": "👁️", "knew": "👁️",
	"victim": "🩸", "victims": "🩸",
	"predict": "🔮", "predicting": "🔮", "predicted": "🔮",
	"engines": "🏎️",
	"rain":    "🌧️", "raining": "🌧️", "rainy": "🌧️",
	"clouds": "☁️", "cloudy": "☁️",
	"build": "🏗️", "builds": "🏗️", "building": "🏗️", "built": "🏗️",
	"institution": "🏛️", "institutions": "🏛️",
	"superintelligence": "🧠",
	"compiler":          "💻", "compilers": "💻", "compiling": "💻",
	"cpp": "💻", "c++": "💻",
	"nix": "❄️", "nixos": "❄️", "nixpkgs": "❄️",
	"risen": "📈", "rises": "📈", "rising": "📈",
	"fallen": "📉", "falls": "📉", "falling": "📉",
	"database": "📊", "databases": "📊", "db": "📊",
	"problem": "❓", "problems": "❓", "problematic": "❓", "problem-solving": "🧩",
	"dots": "⚫", "dot": "⚫", "dotted": "⚫",
	"solution": "💡", "solutions": "💡", "solving": "💡",
	"agent": "🤖", "agents": "🤖", "agentic": "🤖",
	"diplomat": "🤵", "diplomats": "🤵",
	"foreign": "🌍", "foreigners": "🌍", "foreigner": "🌍",
	"oracle": "🔮", "oracles": "🔮", "predictor": "🔮", "predictors": "🔮",
	"dies": "💀",
	"q&a":  "❓",
	"jew":  "✡️", "jewish": "✡️", "rabbi": "✡️", "rabbis": "✡️", "synagogue": "🕍", "synagogues": "🕍", "torah": "✡️",
	"christian": "✝️", "christians": "✝️", "church": "⛪", "churches": "⛪", "bible": "✝️", "bibles": "✝️",
	"muslim": "☪️", "muslims": "☪️", "mosque": "🕌", "mosques": "🕌", "islam": "☪️",
	"buddhist": "☸️", "buddhists": "☸️", "buddhism": "☸️", "temple": "🛕", "temples": "🛕",
	"hindu": "🕉️", "hindus": "🕉️", "hinduism": "🕉️", "mandir": "🛕", "mandirs": "🛕",
	"interest": "💡",
	"rates":    "📈",
	"human":    "👤", "humans": "👤", "humanity": "👥",
	"contrarian": "🤔",
	"website":    "🌐", "websites": "🌐",
	"fight": "🥊", "fights": "🥊", "fighting": "🥊", "fought": "🥊",
	"survey": "📊", "surveys": "📊", "poll": "📊", "polls": "📊",
	"production": "🏭", "productions": "🏭",
	"producing": "🏭", "produced": "🏭",
	"navigation": "🧭", "navigating": "🧭", "navigated": "🧭",
	"markets": "📈", "market": "📈", "marketplace": "🛒", "marketplaces": "🛒",
	"valuation": "⚖️", "valuations": "⚖️", "value": "⚖️", "values": "⚖️",
	"address": "🏠", "addresses": "🏠", "addressing": "🏠", "addressed": "🏠",
	"pointers": "📍", "pointer": "📍", "pointing": "📍", "pointed": "📍",
	"memory": "🧠", "memories": "🧠",
	"package": "📦", "packages": "📦", "packaging": "📦",
	"header": "📰", "headers": "📰", "headlines": "📰", "headline": "📰",
	"performance": "🏎️", "performant": "🏎️", "performing": "🏎️", "performed": "🏎️",
	"upscale": "📈", "upscales": "📈", "upscaling": "📈", "upscaled": "📈",
	"wish": "🌠", "wishes": "🌠", "wishing": "🌠", "wished": "🌠",
	"give up": "🚫", "gives up": "🚫", "giving up": "🚫", "gave up": "🚫",
	"interface": "🖥️", "interfaces": "🖥️", "interfacing": "🖥️", "monitor": "🖥️",
	"night": "🌙", "nights": "🌙", "nighttime": "🌙",
	"nightmare": "👻", "nightmares": "👻", "nightmarish": "👻",
	"studied": "📚", "studying": "📚",
	"teaching": "📚", "teach": "📚", "teaches": "📚", "taught": "📚",
	"clear": "✅", "clears": "✅", "clearing": "✅", "cleared": "✅",
	"recruit": "👥", "recruits": "👥", "recruiting": "👥", "recruited": "👥",
	"path": "🛤️", "paths": "🛤️", "pathway": "🛤️", "pathways": "🛤️",
	"roadmap": "🗺️", "roadmaps": "🗺️", "roadmapping": "🗺️",
	"rust": "🦀", "rustlang": "🦀",
	"quality": "⭐", "qualities": "⭐", "qualitative": "⭐", "qualitatively": "⭐",
	"arch": "🐧", "archlinux": "🐧",
	"defending": "🛡️", "defends": "🛡️", "defended": "🛡️", "defend": "🛡️",
	"science": "🔬", "scientific": "🔬",
	"museum": "🏛️", "museums": "🏛️", "gallery": "🖼️", "galleries": "🖼️",
	"music": "🎵", "musician": "🎤", "musicians": "🎤", "song": "🎶", "songs": "🎶",
	"art": "🎨", "artist": "🎨", "artists": "🎨", "painting": "🖼️", "paintings": "🖼️",
	"photography": "📸", "photo": "📸", "photos": "📸",
	"hollywood": "🎬", "hollywoods": "🎬",
	"movie": "🎥", "movies": "🎥",
	"cinema": "🎥", "cinemas": "🎥", "filmmaking": "🎬",
	"code":       "💻",
	"destroying": "💥", "destroys": "💥", "destroyed": "💥", "destroy": "💥",
	"protest": "✊", "protests": "✊", "protesting": "✊", "protested": "✊",
	"attacking": "⚔️", "attacked": "⚔️",
	"pilot": "✈️", "pilots": "✈️", "piloting": "✈️", "piloted": "✈️",
	"cartoon": "🖼️", "cartoons": "🖼️",
	"picture": "🖼️", "pictures": "🖼️",
	"function": "🔧", "functions": "🔧", "functional": "🔧", "functionality": "🔧",
	"evil": "👿", "villain": "👿", "villains": "👿",
	"approval": "✅", "approvals": "✅", "approve": "✅", "approving": "✅", "approved": "✅",
	"disapproval": "❌", "disapprovals": "❌", "disapprove": "❌", "disapproving": "❌", "disapproved": "❌",
	"rejection": "❌", "rejections": "❌", "reject": "❌", "rejecting": "❌", "rejected": "❌",
	"lost": "💔", "lose": "💔",
	"moat": "🏰", "moats": "🏰",
	"know":      "👁️",
	"energies":  "⚡️️",
	"calculate": "🧮", "calculates": "🧮", "calculating": "🧮", "calculated": "🧮",
	"library": "📚", "libraries": "📚",
	"physics": "⚛️", "physical": "⚛️", "physicist": "⚛️", "physicists": "⚛️",
	"chemist": "⚗️", "chemists": "⚗️",
	"biology": "🧬", "biologist": "🧬", "biologists": "🧬",
	"secrets": "🤫",
	"deleted": "🗑️", "deleting": "🗑️", "delete": "🗑️",
	"compare": "⚖️", "compares": "⚖️", "comparing": "⚖️", "compared": "⚖️",
	"comparison": "⚖️", "comparisons": "⚖️",
	"modern": "🆕", "modernizing": "🆕", "modernized": "🆕",
	"activity": "🏃", "activities": "🏃", "active": "🏃", "actively": "🏃",
	"jet": "✈️", "jets": "✈️",
	"manager": "👨‍💼", "managers": "👨‍💼", "management": "👨‍💼", "managing": "👨‍💼",
	"attacker": "⚔️", "attackers": "⚔️",
	"desktop":  "🖥️",
	"illusion": "🌀", "illusions": "🌀",
	"waf": "🛡️", "dos": "🛡️", "ddos": "🛡️",
	"cloudflare": "☁️",
	"workers":    "🛠️", "worker": "🛠️",
	"browser": "🌐", "browsers": "🌐", "browsing": "🌐", "browse": "🌐",
	"youtube": "📹",
	"email":   "✉️", "emails": "✉️", "mail": "✉️", "mails": "✉️",
	"social": "📱", "socials": "📱",
	"fast": "⚡️", "faster": "⚡️", "fastest": "⚡️", "speed": "⚡️", "speedy": "⚡️",
	"slow": "🐌", "slower": "🐌", "slowest": "🐌",
	"limited": "⏳", "limiting": "⏳", "limits": "⏳", "limit": "⏳",
	"unlimited": "♾️", "unlimiting": "♾️", "unlimits": "♾️", "unlimit": "♾️",
	"connect": "🔗", "connects": "🔗", "connecting": "🔗", "connected": "🔗",
	"connection": "🔗", "connections": "🔗",
	"render": "🎨", "renders": "🎨", "rendering": "🎨", "rendered": "🎨",
	"traffic": "🚦", "traffics": "🚦",
	"image": "🖼️", "images": "🖼️",
	"javascript": "🟨", "js": "🟨",
	"embedded": "🔌", "embedding": "🔌", "embed": "🔌",
	"bare":      "⚙️",
	"baremetal": "⚙️", "bare-metal": "⚙️",
	"controller": "🕹️", "controllers": "🕹️", "controlling": "🕹️", "controlled": "🕹️",
	"register": "📝", "registers": "📝", "registering": "📝", "registered": "📝",
	"c":       "⚙️",
	"silence": "🤫", "whisper": "🤫",
	"disk": "💿", "disks": "💿",
	"password": "🔑", "passwords": "🔑",
	"server": "💻", "servers": "💻",
	"playbook": "♟️",
	"html":     "🌐", "http": "🌐", "https": "🌐",
	"nobel": "🏆", "award": "🏆", "awards": "🏆",
	"bogle": "💡", "boglehead": "💡", "bogleheads": "💡",
	"vti": "🗄️", "etfs": "🗄️",
	"programming": "👨‍💻",
	"maintain":    "🪛", "maintainance": "🪛", "maintains": "🪛", "maintained": "🪛",
	"puzzle": "🧩", "puzzles": "🧩", "puzzled": "🧩", "saving": "🛟", "savings": "🛟",
	"feel": "😑", "feels": "😑", "feelings": "😑",
	"sneaker": "👟", "sneakers": "👟",
	"shoes": "👟", "shoe": "👟",
	"brand": "🏷️", "brands": "🏷️",
	"fashion": "👗", "clothes": "👗", "clothing": "👗", "apparel": "👗",
	"hyper": "🚀", "hypers": "🚀", "hyping": "🚀", "hype": "🚀",
	"design": "🎨", "designs": "🎨", "designing": "🎨", "designed": "🎨",
	"collaboration": "🤝", "collaborate": "🤝", "collaborates": "🤝", "collaborating": "🤝", "collaborated": "🤝",
	"knowledge": "🧠",
	"keboard":   "⌨️", "keyboards": "⌨️",
	"boss": "👔", "bosses": "👔",
	"trial": "⚖️", "trials": "⚖️",
	"world":    "🌍",
	"survivor": "🛟", "survivors": "🛟",
	"rebel": "✊", "rebels": "✊",
	"congress": "🏛️", "congresses": "🏛️",
	"delayed": "⏳", "delays": "⏳", "delaying": "⏳", "delay": "⏳",
	"eagle": "🦅", "eagles": "🦅",
	"ceremony": "🎖️", "ceremonies": "🎖️",
	"effort": "💪", "efforts": "💪",
	"whashington": "🦅", "dc": "🦅",
	"sky": "☁️", "skies": "☁️",
	"duty": "💂", "duties": "💂",
	"ready": "✅", "readies": "✅",
	"landing": "🛬", "lands": "🛬", "landed": "🛬",
	"aim": "🎯", "aims": "🎯", "aiming": "🎯", "aimed": "🎯",
	"service": "🛎️", "services": "🛎️",
	"colorful": "🌈", "color": "🌈", "colors": "🌈", "colour": "🌈", "colours": "🌈",
	"team": "👥", "teams": "👥", "teaming": "👥", "teamed": "👥",
	"smoke": "💨", "smokes": "💨",
	"free": "🆓", "freedom": "🆓",
	"minds": "🧠", "mind": "🧠",
	"crew": "👥", "crews": "👥",
	"flame": "🔥", "flames": "🔥",
	"demolition": "💥", "demolish": "💥", "demolishes": "💥", "demolishing": "💥", "demolished": "💥",
	"aerial": "🛩️",
	"rifle":  "🔫", "rifles": "🔫",
	"budget": "💰", "budgets": "💰", "budgeting": "💰", "budgeted": "💰",
	"landscape": "🏞️", "landscapes": "🏞️",
	"communist": "☭", "communists": "☭", "communism": "☭",
	"joins": "➕", "join": "➕", "joining": "➕", "joined": "➕",
	"leaves": "➖", "leave": "➖", "leaving": "➖", "left": "➖",
	"tactic":  "♟️",
	"seeking": "🔍", "seeks": "🔍", "seek": "🔍", "sought": "🔍",
	"seat": "💺", "seats": "💺",
	"labour": "👷‍♂️", "labors": "👷‍♂️",
	"conservative": "👔", "conservatives": "👔",
	"minister": "🏛️", "ministers": "🏛️",
	"parliament": "🏛️", "parliaments": "🏛️",
	"city": "🏙️", "cities": "🏙️",
	"meet": "🤝", "meets": "🤝", "meeting": "🤝", "met": "🤝",
	"banker": "💼", "bankers": "💼",
	"chicken": "🐔", "chickens": "🐔",
	"protester": "✊", "protesters": "✊",
	"debut": "🎉", "debuts": "🎉", "debuting": "🎉", "debuted": "🎉",
	"fall":      "🍂",
	"released":  "⛓️‍💥",
	"releasing": "⛓️‍💥",
	"gentle":    "🌸", "gently": "🌸",
	"policies": "📜",
	"techy":    "💻", "techies": "💻",
	"coat": "🧥", "coats": "🧥",
	"nike": "👟",
	"feet": "👣", "foot": "👣",
	"killer": "💀", "killers": "💀",
	"resident": "🏠", "residents": "🏠",
	"recover": "💪", "recovers": "💪", "recovering": "💪", "recovered": "💪",
	"sharp": "📈", "sharper": "📈", "sharpest": "📈",
	"boot": "👢", "boots": "👢",
	"fine": "💰", "fines": "💰", "fining": "💰", "fined": "💰",
	"nasa":     "🚀",
	"announce": "📢", "announces": "📢", "announcing": "📢", "announced": "📢",
	"linus": "🐧",
	"git":   "🐙", "github": "🐙",
	"protein": "🧬", "proteins": "🧬",
	"nhs": "🏥", "hospital": "🏥", "hospitals": "🏥",
	"surgery": "🏥", "surgeries": "🏥",
	"community": "👥", "communities": "👥",
	"brutal": "💀", "brutality": "💀",
}

var (
	sortedCountries  []string
	countryRegexps   []*regexp.Regexp
	sortedEmojiTerms []string
	emojiRegexps     []*regexp.Regexp
)

func init() {
	sortedCountries = make([]string, 0, len(CountryToCode))
	for c := range CountryToCode {
		sortedCountries = append(sortedCountries, c)
	}
	sort.Slice(sortedCountries, func(i, j int) bool {
		return len(sortedCountries[i]) > len(sortedCountries[j])
	})

	countryRegexps = make([]*regexp.Regexp, len(sortedCountries))
	for i, country := range sortedCountries {
		pattern := `\b` + regexp.QuoteMeta(country) + `\b`
		countryRegexps[i] = regexp.MustCompile(pattern)
	}

	sortedEmojiTerms = make([]string, 0, len(Emoji))
	for term := range Emoji {
		sortedEmojiTerms = append(sortedEmojiTerms, term)
	}
	sort.Slice(sortedEmojiTerms, func(i, j int) bool {
		return len(sortedEmojiTerms[i]) > len(sortedEmojiTerms[j])
	})

	emojiRegexps = make([]*regexp.Regexp, len(sortedEmojiTerms))
	for i, term := range sortedEmojiTerms {
		pattern := `\b` + regexp.QuoteMeta(term) + `\b`
		emojiRegexps[i] = regexp.MustCompile(pattern)
	}
}

// Convert ISO country code to flag emoji
func countryCodeToFlag(code string) string {
	if len(code) != 2 {
		return ""
	}

	code = strings.ToUpper(code)
	var flag string
	for _, r := range code {
		flag += string(rune(0x1F1E6 + r - 'A'))
	}
	return flag
}

func GetEmojis(title string) string {
	title = strings.ToLower(title)

	// Use small maps to dedupe flags/emojis
	foundFlags := make(map[string]struct{})
	foundEmojis := make(map[string]struct{})

	for i, re := range countryRegexps {
		if re.MatchString(title) {
			code := CountryToCode[sortedCountries[i]]
			if flag := countryCodeToFlag(code); flag != "" {
				foundFlags[flag] = struct{}{}
			}
		}
	}

	for i, re := range emojiRegexps {
		if re.MatchString(title) {
			emoji := Emoji[sortedEmojiTerms[i]]
			if emoji != "" {
				foundEmojis[emoji] = struct{}{}
			}
		}
	}

	// Assemble up to 4 emojis: flags first, then others
	res := make([]string, 0, 4)

	flags := make([]string, 0, len(foundFlags))
	for f := range foundFlags {
		flags = append(flags, f)
	}
	sort.Strings(flags)
	for _, f := range flags {
		if len(res) >= 4 {
			break
		}
		res = append(res, f)
	}

	ems := make([]string, 0, len(foundEmojis))
	for e := range foundEmojis {
		ems = append(ems, e)
	}
	sort.Strings(ems)
	for _, e := range ems {
		if len(res) >= 4 {
			break
		}
		res = append(res, e)
	}

	return strings.Join(res, "")
}
